// Auto-generated. Do not edit.


    declare const enum DXLInstruction {
    DXL_INST_PING = 0x01,
    DXL_INST_READ = 0x02,
    DXL_INST_WRITE = 0x03,
    DXL_INST_REG_WRITE = 0x04,
    DXL_INST_ACTION = 0x05,
    DXL_INST_FACTORY_RESET = 0x06,
    DXL_INST_REBOOT = 0x08,
    DXL_INST_CLEAR = 0x10,
    DXL_INST_STATUS = 0x55,
    DXL_INST_SYNC_READ = 0x82,
    DXL_INST_SYNC_WRITE = 0x83,
    DXL_INST_BULK_READ = 0x92,
    DXL_INST_BULK_WRITE = 0x93,
    }


    declare const enum DXL1_0PacketError {
    DXL1_0_ERR_INPUT_VOLTAGE_BIT = 0,
    DXL1_0_ERR_ANGLE_LIMIT_BIT = 1,
    DXL1_0_ERR_OVERHEATING_BIT = 2,
    DXL1_0_ERR_RANGE_BIT = 3,
    DXL1_0_ERR_CHECKSUM_BIT = 4,
    DXL1_0_ERR_OVERLOAD_BIT = 5,
    DXL1_0_ERR_INSTRUCTION_BIT = 6,
    }


    declare const enum DXL2_0PacketError {
    DXL2_0_ERR_NONE = 0x00,
    DXL2_0_ERR_RESULT_FAIL = 1,
    DXL2_0_ERR_INST_ERROR = 2,
    DXL2_0_ERR_CRC_ERROR = 3,
    DXL2_0_ERR_DATA_RANGE = 4,
    DXL2_0_ERR_DATA_LENGTH = 5,
    DXL2_0_ERR_DATA_LIMIT = 6,
    DXL2_0_ERR_ACCESS = 7,
    }


    declare const enum DXL1_0PacketState {
    DXL1_0_PACKET_PARSING_STATE_IDLE = 0,
    DXL1_0_PACKET_PARSING_STATE_ID = 1,
    DXL1_0_PACKET_PARSING_STATE_LENGTH = 2,
    DXL1_0_PACKET_PARSING_STATE_INST_ERR = 3,
    DXL1_0_PACKET_PARSING_STATE_PARAM = 4,
    DXL1_0_PACKET_PARSING_STATE_CHECK_SUM = 5,
    }


    declare const enum DXL2_0PacketState {
    DXL2_0_PACKET_PARSING_STATE_IDLE = 0,
    DXL2_0_PACKET_PARSING_STATE_RESERVED = 1,
    DXL2_0_PACKET_PARSING_STATE_ID = 2,
    DXL2_0_PACKET_PARSING_STATE_LENGTH_L = 3,
    DXL2_0_PACKET_PARSING_STATE_LENGTH_H = 4,
    DXL2_0_PACKET_PARSING_STATE_INST = 5,
    DXL2_0_PACKET_PARSING_STATE_ERROR = 6,
    DXL2_0_PACKET_PARSING_STATE_PARAM = 7,
    DXL2_0_PACKET_PARSING_STATE_CRC_L = 8,
    DXL2_0_PACKET_PARSING_STATE_CRC_H = 9,
    }


    declare const enum DXLLibErrorCode
    {
    DXL_LIB_OK = 0,
    DXL_LIB_PROCEEDING = 1,

    DXL_LIB_ERROR_NOT_SUPPORTED = 2,
    DXL_LIB_ERROR_TIMEOUT = 3,
    DXL_LIB_ERROR_INVAILD_ID = 4,
    DXL_LIB_ERROR_NOT_SUPPORT_BROADCAST = 5,
    DXL_LIB_ERROR_NULLPTR = 6,
    DXL_LIB_ERROR_LENGTH = 7,
    DXL_LIB_ERROR_INVAILD_ADDR = 8,
    DXL_LIB_ERROR_ADDR_LENGTH = 9,
    DXL_LIB_ERROR_BUFFER_OVERFLOW = 10,
    DXL_LIB_ERROR_PORT_NOT_OPEN = 11,
    DXL_LIB_ERROR_WRONG_PACKET = 12,
    DXL_LIB_ERROR_CHECK_SUM = 13,
    DXL_LIB_ERROR_CRC = 14,
    DXL_LIB_ERROR_INVAILD_DATA_LENGTH = 15,
    DXL_LIB_ERROR_MEMORY_ALLOCATION_FAIL = 16,
    DXL_LIB_ERROR_INVAILD_PROTOCOL_VERSION = 17,
    DXL_LIB_ERROR_NOT_INITIALIZED = 18,
    DXL_LIB_ERROR_NOT_ENOUGH_BUFFER_SIZE = 19,
    }


    declare const enum DXLBaudRate {
    //% block=1M
    BaudRate1M = 1000000,
    //% block=115200
    BaudRate115200 = 115200,
    //% block=57600
    BaudRate57600 = 57600,
    //% block=9600
    BaudRate9600 = 9600,
    }


    declare const enum DXLOperatingMode {
    //% block=Velocity
    OPModeVelocity = 1,
    //% block=Position
    OPModePosition = 3,
    //% block=Extended Position
    OPModeExPosition = 4,
    //% block=PWM
    OPModePWM = 16,
    }

// Auto-generated. Do not edit. Really.
